language: objective-c
env:
  global:
  - PATH=/usr/local/bin:$PATH
  - LC_TYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      sudo: required
script:
  - pod setup
  - pod spec lint
  - xcodebuild -workspace 'BMSCore.xcworkspace' -scheme 'BMSCore iOS' clean build CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO
  - xcodebuild -workspace 'BMSCore.xcworkspace' -scheme 'BMSCore watchOS' clean build CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO
  - xcodebuild -workspace 'BMSCore.xcworkspace' test -scheme 'BMSCore Tests' -destination 'platform=iOS Simulator,name=iPhone 6'
after_script:
  - ./travis-build-trigger.sh 7588419 $TRAVIS_BRANCH $AUTH_TOKEN
  - ./travis-build-trigger.sh 7588425 $TRAVIS_BRANCH $AUTH_TOKEN
